"""Add upload and processing status to attachments

Revision ID: 856cae07cebc
Revises: i405_legacy_failures
Create Date: 2026-09-26 12:59:45.388541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856cae07cebc'
down_revision: Union[str, Sequence[str], None] = 'i405_legacy_failures'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('storage_key', sa.String(length=500), nullable=True))
    op.add_column('attachments', sa.Column('upload_status', sa.String(length=50), nullable=False, server_default='completed'))
    op.add_column('attachments', sa.Column('processing_status', sa.String(length=50), nullable=False, server_default='completed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'processing_status')
    op.drop_column('attachments', 'upload_status')
    op.drop_column('attachments', 'storage_key')
    # ### end Alembic commands ###
